flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
        title = StringField('Titulo', validators=[DataRequired()])
        content = TextAreaField('Contenido', validators=[DataRequired()])
        submit = SubmitField('Publicar')

flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post

main = Blueprint('main', __name__)

@main.route("/")

@main.route("/inicio")
def inicio():
    return render_template('inicio.html', title='inicio')


@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=4)
    return render_template('home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

@main.route("/productos")
def productos():
    return render_template('productos.html', title='Productos')

@main.route("/album")
def album():
    return render_template('album.html', title='album')

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Su descripción fue publicada', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='Nueva publicación', form=form, legend='Nueva Publicación')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Su publicación se actualizo correctamente', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Actualizar Publicación')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Su publicación fue eliminada', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(
            'Cuenta creada correctamente, ya puede iniciar sesión con su cuenta', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(
                'Login incorrecto. Por favor revisar el email y la contraseña', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Su cuenta fue actualizada', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for(
        'static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=4)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Un email fue enviado con las instrucciones para recuperar la contraseña.', 'info')
        return redirect(url_for('login'))
    return render_template('reset_request.html', title='Restablecer Contraseña', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Token invalido o expiro', 'warning')
        return redirect(url_for('main.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(
            'Su contraseña fue actualizada! Ahora usted puede iniciar sesión', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Restablecer contraseña', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
<br></br>
  <div class="col-md-12 container"> 
    <h10>MAS INFORMACIÓN ACERCA DE LOS PRODUCTOS</h10>
    <br> </br>
    <p class='justify-content-around'>En esta sección se explica brevemente los productos que se ofrecen y de que se componen:</p>
    <br>
    
    <a href="{{ url_for('main.productos') }}" target="_blank"> <h10>Juego de la Mariposa</h10>
    </a>
    <br> </br>
    <img width='200px' height='200px' src="{{url_for('static',filename='img/20.jpeg')}}" alt="...">
    <br> </br>
    <h10 >Composición</h10>
    <br>
    <p class='justify-content-around'>Tiene 45 cuerpos de colores variados 
      cuando saque uno en el dado gana cuerpo, tiene 5 cabezas de color morado 
      cuando saque dos unos en los dados gana una cabeza, tiene 1 cola de color 
      roja cuando saque tres unos en los dados gana la cola que solo es una se 
      juega con 5 dados solo participan los unos.</p>
    <br>
    <h10 >Reglas del Juego</h10>
    <br> </br>
    <p class='justify-content-around'>Cuando tire los dados y saque cuatro unos el que tiro tiene derecho a 
      quitarle la cola si no tiene cola le quita una cabeza a todos y podrá usar 
      solo la cola si la necesita para sí mismo el resto se regresa a la caja 
      si no tiene cola o cabeza le quita un cuerpo al que no tenga cola o cabeza 
      y esas fichas regresan a la caja, además todos le pagarán al ganador él 
      valor de la base inicial.</p>
      <br>
    <p class='justify-content-around'>Cuando tire los dados y saque 5 unos ese gana el juego, indiferente de la 
      cantidad que lleve de la mariposa.</p>
    <p class='justify-content-around'>Cuando se tienen las cabezas u gana dos unos se le da dos cuerpos, 
      igualmente con la cola ahí sería tres cuerpos cuando ya la tenga completa
      cabezas y cola.</p>
    <p class='justify-content-around'>Se inicia con una base la acordada. Ejemplo: 200, y cuando se pierda 
      se pone de a 100. Aquí pierde es cuando no saca unos en el primer tiro, 
      si tiro y saco uno sigue jugando y si al segundo tiro no saco unos no 
      pone multa.</p>
     <p class='justify-content-around'>Se juega con cinco dados, cuando le falten 4 cuerpos se tira con 4 
      dados y así a medida que va mermando el número de cuerpos se disminuye 
      el número de dados, cuando le falte cola y cabezas indiferente al número
      de cuerpos se tirará con los 5 dados hasta conseguir cubrir la mariposa 
      con todas las fichas.</p>
      <br>

      <a href="{{ url_for('main.productos') }}" target="_blank"> <h10 >Portacelular</h10>
      </a>
      <br> </br>
      <img width='200px' height='200px' src="{{url_for('static',filename='img/p22.jpeg')}}" alt="...">
      <br> </br>
     
     <p class='justify-content-around'>Este producto su función es poder dejar reposar el celular sobre algo
      mientras vemos algún video, o mientras cargamos nuestro celular, de esta 
      manera tenerlo de forma más cómoda y segura.</p>
      <br>

      <a href="{{ url_for('main.productos') }}" target="_blank"> <h10 >Servilleteros</h10>
      </a>
      <br> </br>
      <img width='200px' height='200px' src="{{url_for('static',filename='img/p11.jpeg')}}" alt="...">
      <br> </br>
     
     <p class='justify-content-around'>Este producto su función es tener las servilletas a la mano, cuando 
      la ubicamos en el comedor, dando un aspecto bonito y vistoso.</p>
      <br>

      <a href="{{ url_for('main.productos') }}" target="_blank"> <h10 >Tapabocas</h10>
      </a>
      <br> </br>
      <img width='200px' height='200px' src="{{url_for('static',filename='img/p33.jpeg')}}" alt="...">
      <br> </br>

      
     <p class='justify-content-around'>Este producto no es un tapabocas tradicional, porque son pintados 
      a mano y le da un toque artístico muy expontaneo y único.</p>
     <br>

     <a href="{{ url_for('main.productos') }}" target="_blank"> <h10 >Alcancias</h10>
     </a>
     <br> </br>
     <img width='200px' height='200px' src="{{url_for('static',filename='img/5.jpeg')}}" alt="...">
     <br> </br>
      
     <p class='justify-content-around'>Este producto su función es poder ahorrar más, es reutilizable y 
      el diseño es personalizable.</p>
     <br>

     <a href="{{ url_for('main.productos') }}" target="_blank"> <h10 >Cofres</h10>
     </a>
     <br> </br>
     <img width='200px' height='200px' src="{{url_for('static',filename='img/58.jpeg')}}" alt="...">
     <br> </br>

     <p class='justify-content-around'>Este producto permite guardar objetos de valor que sean muy 
      importantes, tenerlos de una manera más segura.</p>
     <br>

     <a href="{{ url_for('main.productos') }}" target="_blank"> <h10 >Elefantes</h10>
     </a>
     <br> </br>
     <img width='200px' height='200px' src="{{url_for('static',filename='img/36.jpeg')}}" alt="...">
     <br>

     <p class='justify-content-around'>Este producto son decoraciones para la sala o para el hogar, 
      la visitas de tu hogar se percatarán que es algo que no muchas 
      personas poseen.</p>
     <br>

     <a href="{{ url_for('main.productos') }}" target="_blank"> <h10 >Cubierteros</h10>
     </a>
     <br> </br>
     <img width='200px' height='200px' src="{{url_for('static',filename='img/40.jpeg')}}" alt="...">
     <br>

     <p class='justify-content-around'>Este producto su función es tener los cubiertos a la mano, 
      cuando lo ubicamos en el comedor, dando un aspecto bonito y 
      vistoso.</p>

  </div>
    
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="Descripcion" content="Pagina Web">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="L valencia" />
    <link rel="icon" href="static/img/pintar.png">
    <link rel="stylesheet" media="screen" href="css/style.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="css/bootstrap.min.css">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    

    <!-- scripts -->
    

    {% if title %}
        <title>Creaciones Blog - {{ title }}</title>
    {% else %}
        <title>Creaciones Blog</title>
    {% endif %}
</head>

<body>
    <header class="header site-header">
        
      <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: rgb(109, 91, 207);">
        <div class="nav-item nav-link active nav-link navleter">
          <img width='38px' height='38px' src="{{url_for('static',filename='img/perfil1.png')}}" alt="...">
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active nav-link navleter" href="{{ url_for('main.inicio') }}">Inicio</a>
            <a class="nav-item nav-link active nav-link navleter" href="{{ url_for('main.home') }}">Blog</a>
            <a class="nav-item nav-link active nav-link navleter" href="{{ url_for('main.about') }}">Información</a>
            <a class="nav-item nav-link active nav-link navleter" href="{{ url_for('main.productos') }}">Productos</a>
            <a class="nav-item nav-link active nav-link navleter" href="{{ url_for('main.album') }}">Album de Fotos</a>
          </div>
        </div>
        <!-- Navbar Right Side -->
        <div class="derecha">
          <div class="navbar-nav nav-item navbar-dark active nav-link">
            {% if current_user.is_authenticated %}
                <a class="nav-item nav-link active nav-link navleter" href="{{ url_for('posts.new_post') }}">Nueva Publicación</a>
                <a class="nav-item nav-link active nav-link navleter" href="{{ url_for('users.account') }}">Perfil</a>
                <a class="nav-item nav-link active nav-link navleter" href="{{ url_for('users.logout') }}">Cerrar Sesión</a>
            {% else %}
                <a class="nav-item nav-link active nav-link navleter" href="{{ url_for('users.login') }}">Iniciar Sesión</a>
                <a class="nav-item nav-link active nav-link navleter" href="{{ url_for('users.register') }}">Registrarse</a>
            {% endif %}
          </div>
        </div>
      </nav>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </header>
    <main role="main" class="container">
        
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                        {{ message }}
                        </div>
                    {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
            
            <div class="col-md-4 ">
                <div class="titulo">
                    <h9 class="titulogrande">Creaciones  PLJ</h9>
                    <h8 >Encuentra tus Piezas de manualidades y Decoraciones
                    </h8>
                    <br></br>
                    <a href='https://api.whatsapp.com/send?phone=+573148510845&text=Hola,%20quiero%20conocer%20tu%20catalogo' target="_blank">
                    <img width='40px' height='40px' src="{{url_for('static',filename='img/wasap.png')}}" class="" alt="...">
                    </a>
                    <a href='https://www.instagram.com/creacionesesmiluz/' target="_blank">
                    <img width='30px' height='30px' src="{{url_for('static',filename='img/i.png')}}" class="" alt="...">
                    </a>

                    <a href='https://www.facebook.com/Creaciones-EsmiLuz-104503455315329' target="_blank">
                    <img width='30px' height='30px' src="{{url_for('static',filename='img/f.png')}}" class="" alt="...">
                    </a>

                 </div>
            </div>
        </div>
    </main>

<br>
<br>
<br>

<!-- Footer -->
<div class="footerdiseño">
  <footer class="footerdiseño text-center text-lg-start bg-white text-muted" >

      <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
          <br>
          <span>Contactanos en nuestras redes sociales:</span>
          <i class="fa-solid fa-people-arrows"></i>
        </div>
        <!-- Left -->
      </section>
    
      <!-- Section: Links  -->
      <section class="" >
        <div class="container text-center text-md-start mt-5" >
          <!-- Grid row -->
          <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
              <!-- Content -->
              <h6 class="text-uppercase fw-bold mb-4">
                <i class="fas fa-gem me-3 text-secondary"></i> Sobre nosotros
              </h6>
              <p>
                Creamos productos de valor garantizando la satisfacción de nuestros clientes, en nuestra galería de arte podrás elegir obras personalizadas que harán de tu hogar mucho más elegante y perfecto.
              </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4" >
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">
                Lenguajes
              </h6>
              <p>
                <a class="text-reset">Python</a><br>
                <a class="text-reset">Flask</a><br>
                <a class="text-reset">SQL Alchemy</a><br>
              </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4" >
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">
                  Preguntas Frecuentes
              </h6>
              <p>
                <a href="{{ url_for('main.album') }}"  target="_blank" class="text-reset">Donde puedo ver las Fotos?</a>
              </p>
              <p>
                <a href="{{ url_for('main.productos') }}" target="_blank" class="text-reset">Donde puedo ver los precios?</a>
              </p>
              <p>
                <a href='https://api.whatsapp.com/send?phone=+573148510845&text=Hola,%20quiero%20conocer%20tu%20catalogo' target="_blank" class="text-reset">Donde hablar con un asesor?</a>
              </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">Contactos</h6>
              <p><i class="fas fa-home me-3 text-secondary"></i> Manizales, Caldas </p>
              <p>
                <i class="fas fa-envelope me-3 text-secondary"></i>
                crecionesplj@gmail.com
              </p>
              <p><i class="fas fa-phone me-3 text-secondary"></i> + 57 314 851 084 4</p>
              <br>
              <a href='https://api.whatsapp.com/send?phone=+573148510845&text=Hola,%20quiero%20conocer%20tu%20catalogo' target="_blank">
                  <i class="fa-brands fa-whatsapp me-3 text-secondary"></i>
              </a>
              <a href='https://www.instagram.com/creacionesesmiluz/' target="_blank">
                  <i class="fa-brands fa-instagram me-3 text-secondary"></i>
              </a>

              <a href='https://www.facebook.com/Creaciones-EsmiLuz-104503455315329' target="_blank">
                  <i class="fa-brands fa-facebook-f me-3 text-secondary"></i>
              </a>

              <a href='https://github.com/' target="_blank">
                  <i class="fa-brands fa-github me-3 text-secondary"></i>
              </a>

              <a href='https://www.linkedin.com/' target="_blank">
                  <i class="fa-brands fa-linkedin-in me-3 text-secondary"></i>
              </a>
            </div>
            <!-- Grid column -->
          </div>
          <!-- Grid row -->
        </div>
      </section>
      <!-- Section: Links  -->
    
      <!-- Copyright -->
      <div class="text-center p-4" style="background: rgb(185, 185, 185);" >
        © 2023 Copyright:
        <a class="text-reset fw-bold" href="{{ url_for('main.inicio') }} ">CreacionesPLJ.com</a>
      </div>
      <!-- Copyright -->
    </footer>
</div>
  <!-- Footer -->



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
<br></br>
<br></br>
    <div class="content-section2">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Iniciar Sesión</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                <!--<a href="{{ url_for('users.reset_request') }}">olvido su contraseña</a> tal vez despues-->
            </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small >
            No estas registrado? Click aqui <a class="ml-2" href="{{ url_for('users.register') }}">Registrarse ahora</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
<br></br>
<br></br>
  <article class="media content-section">
      <img class ="rounded-circle article-img" src="{{url_for('static', filename='profile_pics/' + post.author.image_file) }}">
      <div class="media-body">
          <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
          {% if post.author == current_user %}
            <div>
              <a class="btn btn-secondary btn-sm m-1" href="{{ url_for('posts.update_post', post_id=post.id)}}">Actualizar</a>
              <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Eliminar</button>
            </div>
          {% endif %}
          </div>
          <h2 class="article-title">{{ post.title }}</h2>
          <p class="article-content">{{ post.content }}</p>
      </div>
  </article>

  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">¿Estas seguro de eliminar el post?</h5>
          
          <form href="{{ url_for('main.home') }}">
            <input class="btn-close" aria-label="Close"  type="submit" value="X">
          </form>
        </div>
        <div class="modal-footer">
          <form href="{{ url_for('main.home') }}">
            <input class="btn btn-secondary" type="submit" value="Cancelar">
          </form>
          <div>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Eliminar">
          </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}